### ISSUE TITLE
Sponsors and members are displayed weirdly on the about page

### ISSUE THREAD

**Issue by vaishnav-mk** [cdnjs/static-website#123]
## Information
https://www.whatismybrowser.com/w/D9W69X9
### Problem
The about page looks a bit weird, especially on tablets. It's just a long line of members and sponsors with a lot of space left on the right hand side (820x1180)

### What I have tried
I tried using devtools to see if this is the case for other similar viewports as well and it seems like that's the case for screen width between `$mobile: 768px;` and `$breakpoint: 960px;`
### Screenshots
![image](https://user-images.githubusercontent.com/84540554/198939322-96725ab9-57aa-472d-ad08-7f493f92600c.png)

### Possible fixes(?)
I tried working on the issue and came up with a few changes for the website. Do let me know if it's acceptable so I can make a pr for it
- normal desktop
![image](https://user-images.githubusercontent.com/84540554/198939856-a57824fa-fc0e-488e-bd12-11710011b60f.png)
- breakpoint
![image](https://user-images.githubusercontent.com/84540554/198939950-100a7aa5-f929-45f9-8a24-3033f79ec628.png)
- phones
![image](https://user-images.githubusercontent.com/84540554/198940014-ebf18bfc-232d-41ec-bbbc-bf26e56079e7.png)
![image](https://user-images.githubusercontent.com/84540554/198940030-30fee3e8-296f-4d91-b5f8-8f8c7e09d148.png)
- slight animation on hover
![animation](https://i.imgur.com/mFjcHB2.gif)

or:

something that's a bit more subtle than an entire bg color update

![gif](https://i.imgur.com/Jg3X0XE.gif)

![image](https://user-images.githubusercontent.com/84540554/199002202-b3544d4b-cd76-4de6-87a1-4a6356cbe657.png)

`border: 1px solid $primary;`

### Code changes
- members
```css
              .member {
                background: $primary;
                border-radius: $radius;
                display: flex;
                flex-direction: row;
                flex:  calc(50% - #{$whitespace});
                margin: 0 $whitespace $whitespace 0;
                padding: $whitespace;
                transition: all $transition-duration $transition-timing-function;
                
                &:hover {
                  background: $primary-hover;
                  transform: translateY(- calc($whitespace / 2));
                }

                @media screen and (max-width: $breakpoint) {
                  margin: 0 0 $whitespace 0;
                  &:nth-child(odd) {
                    margin-right: $whitespace;
                  }
                }

                @media screen and (max-width: $mobile-sm) {
                  flex-basis: 100%;
                  margin: 0 0 $whitespace 0;
                  &:nth-child(odd) {
                    margin-right: 0;
                  }
                }
              }
```
- sponsors
```css
              @media screen and (max-width: $breakpoint) and (min-width: $mobile) {
                height: 200px;
                width: 200px;
                display: inline-flex;
                margin: 0 $whitespace $whitespace 0;
                img {
                  height: 100%;
                  object-fit: contain;
                  width: 100%;
                }
              }
```
I'm quite new to this so do let me know if I can make changes to suit your needs
